apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: cert-manager
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.19.1
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
