apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: cert-manager
  source:
    chart: cert-manager
    repoURL: oci://quay.io/jetstack/charts/cert-manager
    targetRevision: "v1.18.1"
    helm:
      parameters:
        - name: crds.enabled
          value: "true"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
