apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: longhorn-system
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.9.1
    helm:
      parameters:
        - name: defaultSettings.defaultReplicaCount
          value: "2"
        - name: preUpgradeChecker.jobEnabled
          value: "false"
        - name: service.ui.type
          value: ClusterIP
        - name: ingress.enabled
          value: "true"
        - name: ingress.host
          value: longhorn-192.168.1.42.nip.io
        - name: ingress.ingressClassName
          value: traefik
        - name: ingress.path
          value: /
        - name: ingress.pathType
          value: Prefix
        - name: ingress.tls
          value: "true"
        - name: ingress.tlsSecret
          value: ingress-longhorn-tls
        - name: ingress.annotations.cert-manager\.io/cluster-issuer
          value: my-ca-issuer

  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/ports/0/nodePort
