apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: n8n
  source:
    chart: n8n
    repoURL: oci://8gears.container-registry.com/library/n8n
    targetRevision: "1.0.13"
    helm:
      parameters:
        - name: main.service.type
          value: LoadBalancer
        - name: main.config.n8n.secure_cookie
          value: "false"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
