apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencti
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: opencti
  source:
    chart: opencti
    repoURL: https://devops-ia.github.io/helm-opencti
    targetRevision: 2.0.4
    helm:
      parameters:
        - name: env.APP__ADMIN__EMAIL
          value: admin@example.com
        - name: env.APP__ADMIN__PASSWORD
          value: changeme
        - name: env.APP__ADMIN__TOKEN
          value: b1976749-8a53-4f49-bf04-cafa2a3458c1
        - name: env.APP__BASE_PATH
          value: "/"
        - name: env.APP__HEALTH_ACCESS_KEY
          value: changeme
        - name: env.APP__TELEMETRY__METRICS__ENABLED
          value: "false"
        - name: env.APP__GRAPHQL__PLAYGROUND__ENABLED
          value: "false"
        - name: env.APP__GRAPHQL__PLAYGROUND__FORCE_DISABLED_INTROSPECTION
          value: "false"
        - name: env.ELASTICSEARCH__ENGINE_SELECTOR
          value: opensearch
        - name: env.ELASTICSEARCH__URL
          value: http://opencti-opensearch:9200
        - name: env.MINIO__ENDPOINT
          value: opencti-minio
        - name: env.MINIO__ACCESS_KEY
          value: user
        - name: env.MINIO__SECRET_KEY
          value: changeme
        - name: env.RABBITMQ__HOSTNAME
          value: opencti-rabbitmq
        - name: env.RABBITMQ__PORT_MANAGEMENT
          value: "15672"
        - name: env.RABBITMQ__PORT
          value: "5672"
        - name: env.RABBITMQ__USERNAME
          value: user
        - name: env.REDIS__HOSTNAME
          value: opencti-redis
        - name: env.REDIS__MODE
          value: single
        - name: env.REDIS__PORT
          value: "6379"

        - name: opensearch.enabled
          value: "true"
        - name: opensearch.opensearchJavaOpts
          value: "-Xmx512M -Xms512M"
        - name: opensearch.singleNode
          value: "true"
        - name: opensearch.persistence.enabled
          value: "false"

        - name: minio.enabled
          value: "true"
        - name: minio.mode
          value: standalone
        - name: minio.auth.rootUser
          value: user
        - name: minio.auth.rootPassword
          value: changeme
        - name: minio.persistence.enabled
          value: "false"

        - name: rabbitmq.enabled
          value: "true"
        - name: rabbitmq.replicaCount
          value: "1"
        - name: rabbitmq.clustering.enabled
          value: "false"
        - name: rabbitmq.auth.username
          value: user
        - name: rabbitmq.auth.password
          value: changeme
        - name: rabbitmq.auth.erlangCookie
          value: changeme
        - name: rabbitmq.persistence.enabled
          value: "false"

        - name: ingress.enabled
          value: "true"
        - name: ingress.className
          value: traefik
        - name: ingress.hosts[0].host
          value: opencti-192.168.1.42.local
        - name: ingress.hosts[0].paths[0].path
          value: "/"
        - name: ingress.hosts[0].paths[0].pathType
          value: Prefix
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
