apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentcti
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: opencti
  source:
    chart: opencti
    repoURL: https://devops-ia.github.io/helm-opencti
    targetRevision: 2.0.4
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true