apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencti
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: opencti
  source:
    chart: opencti
    repoURL: https://devops-ia.github.io/helm-opencti
    targetRevision: 2.0.4
    helm:
      parameters:
        - name: env.APP__ADMIN__EMAIL
          value: "admin@example.com"
        - name: env.APP__ADMIN__PASSWORD
          value: "changeme"
        - name: env.APP__ADMIN__TOKEN
          value: "b1976749-8a53-4f49-bf04-cafa2a3458c1"
        - name: env.APP__BASE_PATH
          value: "/"
        - name: env.APP__HEALTH_ACCESS_KEY
          value: "changeme"
        - name: env.APP__TELEMETRY__METRICS__ENABLED
          value: "false"
        - name: env.APP__GRAPHQL__PLAYGROUND__ENABLED
          value: "false"
        - name: env.APP__GRAPHQL__PLAYGROUND__FORCE_DISABLED_INTROSPECTION
          value: "false"
        - name: env.ELASTICSEARCH__ENGINE_SELECTOR
          value: "opensearch"
        - name: env.ELASTICSEARCH__URL
          value: "http://opencti-opensearch:9200"
        - name: env.MINIO__ENDPOINT
          value: "opencti-minio"
        - name: env.MINIO__ACCESS_KEY
          value: "user"
        - name: env.MINIO__SECRET_KEY
          value: "changeme"
        - name: env.RABBITMQ__HOSTNAME
          value: "opencti-rabbitmq"
        - name: env.RABBITMQ__PORT_MANAGEMENT
          value: "15672"
        - name: env.RABBITMQ__PORT
          value: "5672"
        - name: env.RABBITMQ__USERNAME
          value: "user"
        - name: env.REDIS__HOSTNAME
          value: "opencti-redis"
        - name: env.REDIS__PORT
          value: "6379"
        - name: env.REDIS__MODE
          value: "single"

        - name: opensearch.enabled
          value: "true"
        - name: opensearch.fullnameOverride
          value: "opencti-opensearch"
        - name: opensearch.opensearchJavaOpts
          value: "-Xmx512M -Xms512M"
        - name: opensearch.singleNode
          value: "true"
        - name: opensearch.config.opensearch\.yml
          value: "plugins.security.disabled: true"
        - name: opensearch.resources.requests.memory
          value: "512Mi"
        - name: opensearch.resources.requests.cpu
          value: "250m"
        - name: opensearch.resources.limits.memory
          value: "1Gi"
        - name: opensearch.resources.limits.cpu
          value: "500m"
        - name: opensearch.persistence.enabled
          value: "false"

        - name: minio.enabled
          value: "true"
        - name: minio.fullnameOverride
          value: "opencti-minio"
        - name: minio.auth.rootUser
          value: "user"
        - name: minio.auth.rootPassword
          value: "changeme"
        - name: minio.resources.requests.memory
          value: "256Mi"
        - name: minio.resources.requests.cpu
          value: "100m"
        - name: minio.resources.limits.memory
          value: "512Mi"
        - name: minio.persistence.enabled
          value: "false"

        - name: rabbitmq.enabled
          value: "true"
        - name: rabbitmq.fullnameOverride
          value: "opencti-rabbitmq"
        - name: rabbitmq.resources.requests.memory
          value: "256Mi"
        - name: rabbitmq.resources.requests.cpu
          value: "100m"
        - name: rabbitmq.resources.limits.memory
          value: "512Mi"
        - name: rabbitmq.auth.username
          value: "user"
        - name: rabbitmq.auth.password
          value: "changeme"
        - name: rabbitmq.auth.erlangCookie
          value: "changeme"
        - name: rabbitmq.clustering.enabled
          value: "false"
        - name: rabbitmq.networkPolicy.enabled
          value: "false"
        - name: rabbitmq.persistence.enabled
          value: "false"

        - name: redis.enabled
          value: "true"
        - name: redis.fullnameOverride
          value: "opencti-redis"
        - name: redis.resources.requests.memory
          value: "256Mi"
        - name: redis.resources.requests.cpu
          value: "50m"
        - name: redis.resources.limits.memory
          value: "256Mi"
        - name: redis.extraArgs[0]
          value: "--maxmemory=256mb"
        - name: redis.extraArgs[1]
          value: "--proactor_threads=1"
        - name: redis.extraArgs[2]
          value: "--num_shards=1"

        - name: ingress.enabled
          value: "true"
        - name: ingress.hosts[0].host
          value: "opencti-192.168.1.42.nip.io"
        - name: ingress.hosts[0].paths[0].path
          value: "/"
        - name: ingress.hosts[0].paths[0].pathType
          value: "Prefix"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
