apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencti
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: opencti
  source:
    chart: opencti
    repoURL: https://devops-ia.github.io/helm-opencti
    targetRevision: 2.0.4
    helm:
      parameters:
        - name: opensearch.enabled
          value: "true"
        - name: rabbitmq.enabled
          value: "true"
        - name: redis.enabled
          value: "true"
        - name: redis.storage.enabled
          value: "true"
        - name: minio.enabled
          value: "true"

        - name: opensearch.persistence.enabled
          value: "false"
        - name: minio.persistence.enabled
          value: "false"
        - name: rabbitmq.persistence.enabled
          value: "false"

        - name: env.APP__ADMIN__EMAIL
          value: "admin@example.com"
        - name: env.APP__ADMIN__PASSWORD
          value: "changeme123"
        - name: env.APP__ADMIN__TOKEN
          value: "b1976749-8a53-4f49-bf04-cafa2a3458c1"
        - name: env.APP__BASE_URL
          value: "http://opencti.local"

        - name: ingress.enabled
          value: "true"
        - name: ingress.className
          value: "traefik"
        - name: ingress.hosts[0].host
          value: "opencti.local"
        - name: ingress.hosts[0].paths[0].path
          value: "/"
        - name: ingress.hosts[0].paths[0].pathType
          value: "Prefix"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
